name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - master # 當你 push 到 main 分支時會自動觸發部署

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Angular Application
        run: ./node_modules/.bin/ng build --configuration production --base-href /${{ github.event.repository.name }}/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 這裡會自動指定打包好的靜態網頁路徑 (Angular 預設輸出在 dist 專案資料夾下的 browser 中)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/mcu-114-2-web-14131323-final/browser

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
